spring:
  application:
    name: library-management-api

  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:3600000}

file:
  storage:
    location: uploads
    max-size: 5242880
    max-age: 86400000
    allowed-extensions:
      - jpg
      - jpeg
      - png
      - pdf

scheduler:
  file-cleanup:
    enabled: true
    interval: 3600000